// Write go2rtc.yaml from the live device list, so a camera appears with nobody editing YAML.
//
// go2rtc (bundled in the image) is the ONLY media-protocol code in this project: it pulls the bridge's
// one HTTP Annex-B feed per camera and turns it into RTSP / WebRTC / MSE / HLS.
//
// The bridge's `/stream/<sn>` feed is raw Annex-B with NO embedded timing (a P2P elementary stream
// carries none) — confirmed locally (ffmpeg 8.1.2, a synthetic bursty raw-H264 HTTP source standing in
// for the real P2P feed, see PR discussion) that go2rtc's plain `#video=copy` (a stream copy, no `-r`
// hint) doesn't just risk corruption, it fails outright: any timestamped muxer (RTSP/RTP included, not
// just the matroska this was verified against) refuses a packet with no PTS/DTS and the stream never
// starts. `-r <fps>` alone — the fix that worked for this project's sibling `eufy-security-ws-RDB` fork
// — did NOT reproduce as sufficient here; only a real decode+encode pass (which derives its own
// timing from decoded frame order, independent of what the input lacks) produced clean, correctly-timed
// output in that same local test. So this uses go2rtc's `video=h264` transcode template, not `copy`.
//
// Trade-off, stated plainly: transcoding costs real per-stream CPU that stream-copy doesn't — exactly
// what the sibling fork's own history found NAS-class hardware struggles with with two concurrent
// streams. This is the safe default to actually get streaming working at all; if CPU load turns out to
// be a real problem on specific hardware, that's the next thing to optimize (test on real hardware
// first, per this project's own practice — don't pre-guess it away).
//
// `-r 15` matches the fps the sibling fork consistently measured across its real Eufy cameras; override
// via BRIDGE_STREAM_FPS if a specific camera model's real rate is confirmed to differ.
//
// The file contains real serials, so it is gitignored and generated at startup.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

// A device that carries live video: a describeDevice() summary with a `stream` path (capabilities
// include camera/video). This matches what HA turns into a camera entity — using deviceClass here
// would miss a camera the SDK downgrades to "other" for sitting behind a HomeBase (not direct P2P).
const isCamera = (d) => Boolean(d.stream);

export async function writeGo2rtcConfig(cfg, devices) {
  const cams = devices.filter(isCamera);
  const fps = cfg.streamFps || 15;
  const lines = [
    "# generated by ha-eufy-sdk-bridge at startup — do not edit (contains real serials)",
    "api:",
    '  listen: ":1984"',
    "rtsp:",
    '  listen: ":8554"',
    "webrtc:",
    '  listen: ":8555"',
    // go2rtc's ffmpeg module defaults its OWN subprocess to `-v error`, which swallows exactly the
    // warnings (e.g. "Timestamps are unset in a packet") that would explain a stream failing on real
    // camera footage the way it didn't on the synthetic feed this was verified against locally. Set
    // GO2RTC_FFMPEG_LOG=debug (redeploy required — this file is regenerated fresh at every boot) to see
    // it; default matches go2rtc's own quiet default so normal operation isn't noisier than before.
    "log:",
    `  ffmpeg: ${cfg.go2rtcFfmpegLog || "error"}`,
    "streams:",
  ];
  for (const d of cams) {
    // A stream id per camera serial; the source is this bridge's own HTTP feed. `input=-r <fps> -i
    // {input}` overrides go2rtc's default bare `-i {input}` so the untimed raw feed gets a declared
    // frame rate before ffmpeg's h264 encoder (video=h264) derives real timestamps from it.
    const src = `http://${cfg.selfHost}:${cfg.port}/stream/${d.sn}`;
    lines.push(`  ${d.sn}: "ffmpeg:${src}#video=h264#input=-r ${fps} -i {input}"`);
  }
  const yaml = lines.join("\n") + "\n";
  await mkdir(dirname(cfg.go2rtcConfig), { recursive: true }).catch(() => {});
  await writeFile(cfg.go2rtcConfig, yaml, "utf8");
  return cams.map((d) => d.sn);
}
