// Write go2rtc.yaml from the live device list, so a camera appears with nobody editing YAML.
//
// go2rtc (bundled in the image) is the ONLY media-protocol code in this project: it pulls the bridge's
// one HTTP Annex-B feed per camera and turns it into RTSP / WebRTC / MSE / HLS.
//
// The bridge's `/stream/<sn>` feed is raw Annex-B with NO embedded timing (a P2P elementary stream
// carries none) — confirmed locally (ffmpeg 8.1.2, a synthetic bursty raw-H264 HTTP source standing in
// for the real P2P feed, see PR discussion) that go2rtc's plain `#video=copy` (a stream copy, no `-r`
// hint) doesn't just risk corruption, it fails outright: any timestamped muxer (RTSP/RTP included, not
// just the matroska this was verified against) refuses a packet with no PTS/DTS and the stream never
// starts. `-r <fps>` alone — the fix that worked for this project's sibling `eufy-security-ws-RDB` fork
// — did NOT reproduce as sufficient here; only a real decode+encode pass (which derives its own
// timing from decoded frame order, independent of what the input lacks) produced clean, correctly-timed
// output in that same local test. So this uses go2rtc's `video=h264` transcode template, not `copy`.
//
// Trade-off, stated plainly: transcoding costs real per-stream CPU that stream-copy doesn't — exactly
// what the sibling fork's own history found NAS-class hardware struggles with with two concurrent
// streams. This is the safe default to actually get streaming working at all; if CPU load turns out to
// be a real problem on specific hardware, that's the next thing to optimize (test on real hardware
// first, per this project's own practice — don't pre-guess it away).
//
// `-r 15` matches the fps the sibling fork consistently measured across its real Eufy cameras; override
// via BRIDGE_STREAM_FPS if a specific camera model's real rate is confirmed to differ.
//
// The file contains real serials, so it is gitignored and generated at startup.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

// A device that carries live video: a describeDevice() summary with a `stream` path (capabilities
// include camera/video). This matches what HA turns into a camera entity — using deviceClass here
// would miss a camera the SDK downgrades to "other" for sitting behind a HomeBase (not direct P2P).
const isCamera = (d) => Boolean(d.stream);

/**
 * The exact `ffmpeg:...#video=h264#input=...` source string go2rtc uses for one camera's stream.
 * Shared with go2rtc-recover.mjs, which has to rebuild this identically when re-PUTting a stream
 * that go2rtc's own exec-producer race (see that file) left stuck — any drift between the two
 * would mean a "recovered" stream comes back with different transcode params than every other one.
 *
 * A serial listed in cfg.go2rtcCopyAsyncDevices gets `video=copy#async` instead of this project's
 * default `video=h264` full transcode — an EXPERIMENTAL per-device trial of the community fork's
 * PR #64 fix (see config.mjs): a stream-copy re-stamped by go2rtc's own `-use_wallclock_as_timestamps
 * 1 -async 1` (native go2rtc, `internal/ffmpeg/ffmpeg.go`) costs none of the transcode's CPU, IF it
 * turns out to produce clean output on this project's actual camera feeds — not yet confirmed on real
 * hardware here, which is exactly why this is opt-in rather than the new default.
 */
export function go2rtcSourceUrl(cfg, sn) {
  const fps = cfg.streamFps || 15;
  const src = `http://${cfg.selfHost}:${cfg.port}/stream/${sn}`;
  const video = cfg.go2rtcCopyAsyncDevices?.has(sn) ? "copy#async" : "h264";
  return `ffmpeg:${src}#video=${video}#input=-r ${fps} -i ${src}`;
}

export async function writeGo2rtcConfig(cfg, devices) {
  const cams = devices.filter(isCamera);
  const lines = [
    "# generated by ha-eufy-sdk-bridge at startup — do not edit (contains real serials)",
    "api:",
    `  listen: ":${cfg.go2rtcApiPort}"`,
    "rtsp:",
    '  listen: ":8554"',
    "webrtc:",
    '  listen: ":8555"',
    // go2rtc's ffmpeg module defaults its OWN subprocess to `-v error`, which swallows exactly the
    // warnings (e.g. "Timestamps are unset in a packet") that would explain a stream failing on real
    // camera footage the way it didn't on the synthetic feed this was verified against locally.
    //
    // Raising ONLY `ffmpeg` here is not enough to actually SEE that output, though — confirmed by
    // reading go2rtc's own source: the process that spawns ffmpeg and decides whether to forward its
    // stderr into go2rtc's visible logs at all is a SEPARATE internal module ("exec"), whose own level
    // this never touched, so ffmpeg could be producing detail that go2rtc was silently discarding.
    // `level` (unset unless GO2RTC_LOG_LEVEL is given, so normal operation keeps go2rtc's own built-in
    // default rather than us silently overriding it) is the global fallback every module without its
    // own override uses, "exec" included — so both need to move together to see anything at all. Set
    // BOTH GO2RTC_FFMPEG_LOG=debug and GO2RTC_LOG_LEVEL=debug (redeploy required — this file is
    // regenerated fresh at every boot) to diagnose a stream that won't play.
    "log:",
    `  ffmpeg: ${cfg.go2rtcFfmpegLog || "error"}`,
    ...(cfg.go2rtcLogLevel ? [`  level: ${cfg.go2rtcLogLevel}`] : []),
    "streams:",
  ];
  for (const d of cams) {
    // A stream id per camera serial; the source is this bridge's own HTTP feed. `input=-r <fps> -i <src>`
    // overrides go2rtc's default bare `-i {input}` so the untimed raw feed gets a declared frame rate
    // before ffmpeg's h264 encoder (video=h264) derives real timestamps from it.
    //
    // Deliberately spells out `src` here rather than using go2rtc's own `{input}` placeholder (its own
    // docs show `#input=-timeout {timeout} -i {input}` as the normal way to write this). Confirmed via
    // go2rtc's source (internal/streams/producer.go) that this specific placeholder is special: ANY
    // stream source containing the literal substring "{input}" makes go2rtc register it as a "template"
    // producer whose real `url` is only ever filled in by a later SetSource() call — one that never
    // happens for a plain top-level camera stream, so `prod.url` stays permanently empty. That empty url
    // then satisfies `add_consumer.go`'s loop-request guard (`prod.url == consumer.GetSource()`, both
    // empty) and every consumer gets silently skipped in milliseconds — go2rtc never even dials, so
    // nothing reaches this bridge, and ffmpeg is never wrong because it's never run. Confirmed end to end
    // on real hardware: the exact same transcode invoked directly (bypassing go2rtc) plays 300 clean
    // frames with zero errors; only the `{input}`-shaped config line fails. Substituting the real URL
    // here avoids the literal placeholder entirely, so this bug doesn't trigger.
    lines.push(`  ${d.sn}: "${go2rtcSourceUrl(cfg, d.sn)}"`);
  }
  const yaml = lines.join("\n") + "\n";
  await mkdir(dirname(cfg.go2rtcConfig), { recursive: true }).catch(() => {});
  await writeFile(cfg.go2rtcConfig, yaml, "utf8");
  return cams.map((d) => d.sn);
}
